//
// Generated file, do not edit! Created by opp_msgtool 6.0 from apps/PLRut/CapacityPackets.msg.
//

#ifndef __CAPACITYPACKETS_M_H
#define __CAPACITYPACKETS_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class CapacityPacket;
#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

/**
 * Class generated from <tt>apps/PLRut/CapacityPackets.msg:5</tt> by opp_msgtool.
 * <pre>
 * class CapacityPacket extends inet::FieldsChunk
 * {
 *     unsigned int IDtalk;
 *     string carId;
 *     int omnetIndex = -1;
 *     string currentEdge;
 *     string destinationEdge;
 *     string routeEdges;
 *     bool arrived;
 *     bool hasNewRoute;
 *     bool wait;
 *     string newRouteEdges;
 * }
 * </pre>
 */
class CapacityPacket : public ::inet::FieldsChunk
{
  protected:
    unsigned int IDtalk = 0;
    omnetpp::opp_string carId;
    int omnetIndex = -1;
    omnetpp::opp_string currentEdge;
    omnetpp::opp_string destinationEdge;
    omnetpp::opp_string routeEdges;
    bool arrived = false;
    bool hasNewRoute = false;
    bool wait = false;
    omnetpp::opp_string newRouteEdges;

  private:
    void copy(const CapacityPacket& other);

  protected:
    bool operator==(const CapacityPacket&) = delete;

  public:
    CapacityPacket();
    CapacityPacket(const CapacityPacket& other);
    virtual ~CapacityPacket();
    CapacityPacket& operator=(const CapacityPacket& other);
    virtual CapacityPacket *dup() const override {return new CapacityPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual unsigned int getIDtalk() const;
    virtual void setIDtalk(unsigned int IDtalk);

    virtual const char * getCarId() const;
    virtual void setCarId(const char * carId);

    virtual int getOmnetIndex() const;
    virtual void setOmnetIndex(int omnetIndex);

    virtual const char * getCurrentEdge() const;
    virtual void setCurrentEdge(const char * currentEdge);

    virtual const char * getDestinationEdge() const;
    virtual void setDestinationEdge(const char * destinationEdge);

    virtual const char * getRouteEdges() const;
    virtual void setRouteEdges(const char * routeEdges);

    virtual bool getArrived() const;
    virtual void setArrived(bool arrived);

    virtual bool getHasNewRoute() const;
    virtual void setHasNewRoute(bool hasNewRoute);

    virtual bool getWait() const;
    virtual void setWait(bool wait);

    virtual const char * getNewRouteEdges() const;
    virtual void setNewRouteEdges(const char * newRouteEdges);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CapacityPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CapacityPacket& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline CapacityPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<CapacityPacket*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __CAPACITYPACKETS_M_H

